# Utiliser une image de Node.js comme base
FROM node:18-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code source
COPY . .

# Construire l'application Next.js
RUN npm run build

# Exposer le port sur lequel Next.js va tourner
EXPOSE 3000

# Démarrer l'application
CMD ["npm", "start"]
